version: '3.2'

services:
  db:
    image: 'postgres:12-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: 'redis:6.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'
  webpacker:
    build:
      .
    volumes:
      - .:/project
      - /project/node_modules
    command: 'bin/webpack-dev-server'
    ports:
      - '3035:3035'
    env_file:
      - .env.docker
  web:
    depends_on:
      - 'db'
      - 'redis'
      - 'webpacker'
      - 'cable'
    build: .
    volumes:
      - .:/project
      - type: tmpfs
        target: /project/tmp/pids/
    ports:
      - '3000:3000'
    env_file:
      - .env.docker
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    volumes:
      - .:/project
    command: bundle exec sidekiq -q qwizard_reactive_production_default
    env_file:
      - .env.docker
  cable:
    depends_on:
      - 'redis'
    build: .
    ports:
      - '28080:28080'
    volumes:
      - .:/project
    env_file:
      - .env.docker
    command: bundle exec puma -p 28080 cable/config.ru
volumes:
  redis:
  postgres:
